name: CI

on: [push, pull_request]

jobs:
  verify:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Set up Python 3.9
        uses: actions/setup-python@v1
        with:
          python-version: '3.9'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -e .
      - name: Run Black
        uses: psf/black@stable
      - name: Run unit tests
        run: |
          pytest --cov-report xml --cov=src --ignore=src/new_api --ignore=services/ --junit-xml=test_report.xml -m "not integration"
